apiVersion: v1
kind: Service
metadata:
  name: cd-docker-web-service
  namespace: cd-lab
spec:
  type: NodePort
  selector:
    app: cd-docker-web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
